package com.gabriel.covid19stats

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

/**
 * The main entry point for the Covid19Stats Flutter application on Android.
 * This class sets up the Flutter engine and registers any necessary plugins.
 */
class MainActivity: FlutterActivity() {
    /**
     * Configures the Flutter engine with any necessary plugins or settings.
     * This method is called automatically by the Flutter framework when the engine is created.
     *
     * @param flutterEngine The Flutter engine to configure.
     */
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        // Registers any plugins that have been generated by the Flutter framework.
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}

